---
channel: edge
addons:
  tvheadend:
    repository: dfigus/addon-tvheadend
    target: tvheadend
    image: ghcr.io/dfigus/tvheadend/{arch}
  usb-test:
    repository: dfigus/addon-usb-test
    image: ghcr.io/dfigus/usb-test/{arch}
