---
name: Repository Update Manual

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      addon:
        description: 'Addon to update'
        required: true
        default: 'addon-solarflow-control'
        type: string
      force:
        description: 'Force Update'
        required: false
        default: false
        type: boolean

jobs:
  whatever:
    name: Running updater for ${{ inputs.addon }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.name "atrox06"
          git config --global user.email "41265009+atrox06@users.noreply.github.com"

      - name: Install repository-updater
        run: |
          pip install repository-updater

      - name: 🚀 Run Repository Updater
        run: |
          repository-updater --addon ${{ inputs.addon }} --repository ${{ github.repository }} --token ${{ secrets.UPDATER_TOKEN }} --force ${{ inputs.force }}
