---
name: Repository Update Manual

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      addon:
        description: 'Addon to update'
        required: true
<<<<<<< HEAD
        default: 'addon-solarflow-control'
=======
        default: 'solarflow-control'
>>>>>>> d5cde86 (Update Solarflow Control configuration and README for repository ownership and version changes)
        type: string
      force:
        description: 'Force Update'
        required: false
        default: false
        type: boolean

jobs:
  whatever:
    name: Running updater for ${{ inputs.addon }}
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run Repository Updater
        uses: hassio-addons/repository-updater@v1
        with:
          addon: ${{ inputs.addon }}
          repository: ${{ github.repository }}
          token: ${{ secrets.UPDATER_TOKEN }}
          force: ${{ inputs.force }}
